title: Landon James
logo: /IMG_5537.jpeg
description: Recent Data Science graduate with a Bachelor of Science degree, showcasing a wealth of educational accomplishments and hands-on projects. Eager to embark on a career in Data Science, recognized for dedication, hard work, and a knack for quick learning. Ready to apply skills to practical challenges in the field.
show_downloads: true
theme: jekyll-theme-minimal
