title: Landon James
author: Landon James

logo: /IMG_5537.jpeg
description: Recent Data Science graduate with a Bachelor of Science degree, showcasing a wealth of educational accomplishments and hands-on projects. Eager to embark on a career in Data Science, recognized for dedication, hard work, and a knack for quick learning. Ready to apply skills to practical challenges in the field.

show_downloads: true
theme: jekyll-theme-minimal

navbar-links:
  About Me: "aboutme"
  Resources:
    - Data Preprocessing: "https://github.com/LandonJames1/Portfolio/blob/main/proj3_data_preprocess.ipynb"
    - Machine Learning: "https://github.com/LandonJames1/Portfolio/blob/main/proj3_machine_learning.ipynb"
